### ISSUE TITLE
Missing file "\Shinka\ThreadLog\XF\Entity\Forum.php".

### ISSUE THREAD

**Issue by spark108** [kalynrobinson/xf2_threadlog#1]
En: There is no file "\Shinka\ThreadLog\XF\Entity\Forum.php", as well as a class extension for this entity.
Ru: Отсутствует файл "\Shinka\ThreadLog\XF\Entity\Forum.php", а так же расширение класса для этой сущности.

**Comment by kalynrobinson** [comment]
@spark108 Have you received an error about this on installation?

No class extension for the Forum entity should be necessary. The forum's structure is extended in `Shinka/ThreadLog/Listener.php`, to add the new thread log property; and the ACP save behavior is extended in `Shinka/ThreadLog/XF/Pub/Controller/Forum.php`. Is there a reason an entity extension would be necessary here?

**Comment by spark108** [comment]
Shinka/ThreadLog/Listener.php, is not registered in the control panel as an event handler. Error:
`InvalidArgumentException: Unknown column shinka_thread_log on relation Forum (XF:Forum) in src/XF/Mvc/Entity/Finder.php at line 1410`

**Comment by kalynrobinson** [comment]
This has been resolved as of 1.0.0 Beta 4.
